Add Migration Address
Alvesx3/Developers pull request #30
Opened 2021-08-16 19:41 UTC by LorenzoMichelotti

#19

2021-08-16 19:41 UTC, Alvesx3 approved these changes, later dismissed

2021-08-16 19:42 UTC, assi23 submitted a review, later dismissed

2021-08-16 19:47 UTC, milleouriques submitted a review, later dismissed

2021-08-16 20:10 UTC, maykondgranemann requested changes

2021-08-16 20:10 UTC, maykondgranemann commented on Developers/Data/Context/DevContext.cs
> +        DbSet<Address> addresses { get; set; }
Alterar letra maiuscula

2021-08-16 20:15 UTC, LorenzoMichelotti commented on Developers/Data/Context/DevContext.cs
> +        DbSet<Address> addresses { get; set; }
prontinho!!

2021-08-16 20:16 UTC, milleouriques approved these changes

2021-08-16 20:16 UTC, Alvesx3 approved these changes

2021-08-17 18:27 UTC, assi23 approved these changes

2021-08-17 19:01 UTC, Alvesx3 approved these changes

2021-08-17 19:08 UTC, milleouriques approved these changes

2021-08-17 19:24 UTC, closed without merging